# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Yepoleb"
description:        "Blogging about programming, electronics and Linux"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//yepoleb.github.io"
author:             "Yepoleb"

# URL
baseurl:            ""
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "/about"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

